name: "erick"
description: "3.x"

runs:
  using: docker
  image: ubuntu-latest

on:
  push:
    branches:
      - main # substitua pelo nome da sua branch principal

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # substitua pelo número da versão do Python que deseja utilizar

      - name: Instalar dependências
        run: pip install -r requirements.txt # substitua pelo comando de instalação das dependências do seu projeto

      - name: Executar script Python
        run: python script.py # substitua pelo comando para executar o seu script Python
